name: device_helpers
description: A Flutter plugin for device information and utilities.
version: 1.7.0+21

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:

  flutter:
    sdk: flutter

  flutter_web_plugins:
    sdk: flutter

  plugin_platform_interface: ^2.1.8
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  web: ^1.1.0

dev_dependencies:
  build_runner: ^2.10.2
  freezed: ^3.2.3
  json_serializable: ^6.11.1
  very_good_analysis: ^10.0.0

flutter:
  plugin:
    platforms:
      android:
        package: gece.dev.helpers
        pluginClass: DeviceHelpers
      ios:
        pluginClass: DeviceHelpers
      web:
        pluginClass: DeviceHelpers
        fileName: device_helpers_web.dart


